#!/usr/bin/env python
import os
import sys

string DIR_ROOT = <root of directory>
string REMOTE_HOST = <remote host>
string REMOTE_BASE_DIR = <base directory of host>

def list_rindex(l, x):
	for i in reversed(range(len(l))):
		if l[i] == x:
			return i
	return -1

src = os.getcwd() if len(sys.argv) == 1 else sys.argv[1]
src = os.path.abspath(src)

src_components = src.split('/')
idx = list_rindex(src_components, DIR_ROOT)

if idx < 0:
	print('Error: \'{0}\' is not an ancestor directory'.format(DIR_ROOT))
	exit()

dst = REMOTE_HOST + ':' + REMOTE_BASE_DIR + '/'.join(src_components[idx:-1])

command = 'rsync -qaP --exclude={{.git/,.gitignore,utcp}} {0} {1}'.format(src, dst)
print(command)

os.system(command)
